### ISSUE TITLE
Unknown properties.

### ISSUE THREAD

**Issue by vrurg** [css-raku/CSS-Properties-raku#20]
I'm just have realized that the module just drops unknown properties. I tried to use it to parse `style` attribute of SVG nodes where they use their own custom props. But it seems there are currently no chances I could pull out anything useful out of it.

Have I chosen a wrong tool for the task?

**Comment by vrurg** [comment]
Ok, my bad. I overlooked `%extensions`. Probably can manage with it. But there is a question about the meaning of `coerce` key: is its return value used somehow? Because no matter what it returns the property ends up with the original string value.

**Comment by dwarring** [comment]
Sorry not well documented. `coerce` is used to indicate the data-type for validation and serialization.  A quick example:
```
my $module = CSS::Module::CSS3.module: :%extensions;
my $css = CSS::Properties.new( :$module, );
$css."-my-align"() = 'left';
$css."-my-span"() = 42;
$css."-my-string"() = 'xxxx';
$css."-my-id"() = 'yyy';
say $css.Str;    #output: -my-align:left; -my-id:#yyy; -my-span:42; -my-string:'xxxx';
 ```
In particular, these are serialised as numbers, ids, keywords or quoted strings.

**Comment by dwarring** [comment]
I found this [list of SVG properties](https://www.w3.org/TR/SVG/propidx.html).

I think this might sit better with `CSS::Properties` if there was a dedicated `CSS::Module::SVG` module for the above properties. Hypothetically:
```
my CSS::Module::SVG $module .= new;
my CSS::Properties $css .= new: :$module;
```
I'm happy to have a look at creating it, if it might be useful.

**Comment by dwarring** [comment]
^^ I think its a useful addition to`CSS::Module` anyway

**Comment by vrurg** [comment]
I have found the same list too and it turned out to be really helpful. Though my purpose is to extract some coordinates from the output of `pdftocairo` tool where they are likely to use a very limited subset of the properties.

With regard to `&coerce`, I found it used with `default` only. The actual data is not fed into it. Guess, it's a bug?

**Comment by dwarring** [comment]
Agree it should be calling the `&coerce` method. It was on 'rw' accessor, but not parsing.

CSS::Properties 0.9.0 has been released now calls the coerce method when parsing to allow checking or conversion of the value.

This release also includes a bumped CSS::Module and has an initial release of CSS::Module::SVG available. CSS::Properties::Optimizer needed a few teaks to handle the `marked` and `stroke-dasharray` properties.

In terms of this being the right tool. It geared towards uses like rendering, validation and optimization where a more detailed  knowledge of properties is needed. It may be OK, but if performance is an issue, it hasn't been optimized and it's not particularly fast.

**Comment by vrurg** [comment]
Fantastic! Both coercion and the SVG module! 

Optimization doesn't worry me at this point.

I think this issue can be closed now. Thank you!
